### ISSUE TITLE
Mesonic cannot be installed without .git folder

### ISSUE THREAD

**Issue by aleneum** [interactive-sonification/mesonic#1]
Archives provided by Github releases (tar/zip) cannot be installed since they do not contain a `.git` folder required by `setuptools-scm`.

```
$pip install -e ".[notebooks]"

  LookupError: setuptools-scm was unable to detect version for C:\Users\alneuman\sciebo\documents\2022\ma_dreinsch\mesonic-0.1.0.

  Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
```

Extract the archive and running `git init` inside the workspace is a workaround but probably not the intended way of installation.

**Comment by dreinsch** [comment]
Setting the `parentdir_prefix_version` configuration key of `setuptools-scm` to `mesonic-` should fix this issue according to https://github.com/pypa/setuptools_scm/#configuration-parameters
