### ISSUE TITLE
setup.cfg installs an incompatible version of sc3nb

### ISSUE THREAD

**Issue by aleneum** [interactive-sonification/mesonic#2]
The necessity of installing sc3nb as mentioned in `Readme.rst` can be avoided by referencing the repository in the dependency section. I know this can be done via `requirements.txt`  or `pyproject.toml` which makes be confident that this should also be possible with `setup.cfg`. Maybe [PEP 0508](https://peps.python.org/pep-0508/) contains a lead.

**Comment by dreinsch** [comment]
Thank you for the notice. I agree that this is not an optimal solution but a new version of sc3nb should be released soon and then a specially defined dependency won't be necessary anymore.
