### ISSUE TITLE
Optional target 'notebook' lacks notebook dependency

### ISSUE THREAD

**Issue by aleneum** [interactive-sonification/mesonic#4]
When installing mesonic as described in the `Readme.rst` with optional requirements for `notebook` Jupyter and notebook are not installed as mesonic does not depend on them. Maybe `notebook` should be added as a requirement in `setup.cfg`.

**Comment by aleneum** [comment]
Furthermore, `ipywidgets` which is used in mesonic-pmson should probably also be a dependency.

**Comment by dreinsch** [comment]
Thank you for reporting the missing dependencies.

`ipywidgets` will definitely be added to the `notebook` extra of mesonic.

Regarding the `notebook` package I was hesitant to add it as I like to use JupyterLab from the base conda environment with [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) and adding the single kernels by installing `ipykernel`

But I agree that the notebook extra should be functioning without further setups and it would be good to add `notebook` to the extra.
Maybe an extra named `ipykernel` should be added were the `notebook` dependency is replaced by the `ipykernel` and both depend using [interpolation](https://stackoverflow.com/a/67712787) on a example extra which defines the basic dependencies like `ipywidgets` and so on

**Comment by aleneum** [comment]
Splitting targets/extras sounds like a good plan. A target called "notebook" should actually work with notebooks.
